baseurl: https://bookishmusings.github.io/
languageCode: en-US
enableEmoji: true
title: Bookish Musings by A
theme: digital-garden
author: mynameisa
relativeURLs: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: about
      url: /about/about
      weight: 2
    - name: reviews
      url: /about/
      weight: 3
    - name: roundups
      url: /roundups/
      weight: 4
    - name: subscribe
      url: /subscribe/subscribe
      weight: 5
      
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
